name = "RobCannon"
license = "MIT"
licenselink = "https://github.com/RobCannon/RobCannon.github.io/blob/main/LICENSE"
description = "A professional profile for Rob Cannon."
homepage = "https://RobCannon.github.io"
tags = [
  "blog",
  "dark mode",
  "minimal",
  "personal",
  "responsive"
]
features = ["dark mode"]
min_version = "0.41.0"

[author]
  name = "Rob Cannon"
  homepage = "https://RobCannon.github.io"
